name: Crypto News Bot

on:
  schedule:
    - cron: "0 1,5,9,13 * * *"  # 8h, 12h, 16h, 20h
    - cron: "0 3,11 * * *"      # 10h, 18h (giờ VN)
  workflow_dispatch:            #

jobs:
  send-news:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 1,5,9,13 * * *'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Send news to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: node send-news.js news

  send-trend:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 3,11 * * *'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Send trend to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: node send-news.js trend