name: Crypto News Bot

on:
  schedule:
    - cron: "0 1 * * *"   # 8h VN (1h UTC)
    - cron: "0 3 * * *"   # 10h VN (3h UTC)
    - cron: "0 5 * * *"   # 12h VN (5h UTC)
    - cron: "0 9 * * *"   # 16h VN (9h UTC)
    - cron: "0 11 * * *"  # 18h VN (11h UTC)
    - cron: "0 13 * * *"  # 20h VN (13h UTC)
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Send news to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node send-news.js news